name: Update all git modules

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:
    name: Update all git modules
    runs-on: ubuntu-latest
    steps:
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update git modules
        run: ./update-git-modules.zsh
        shell: zsh {0}

      - name: Add, commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'chore: update git modules'
          author-name: 'Yash-Singh1'
          author-email: saiansh2525@gmail.com
